[package]
name = "ryframe-generator"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
description.workspace = true

[features]
default = []
schema-import = [
    "dep:ryframe-kernel",
    "dep:ryframe-tenant-db",
    "dep:sea-orm",
]

[dependencies]
ryframe-kernel = { path = "../ryframe-kernel", optional = true }
ryframe-tenant-db = { path = "../ryframe-tenant-db", default-features = false, features = ["connection"], optional = true }
sea-orm = { workspace = true, optional = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
sha2 = { workspace = true }
hex = { workspace = true }
tempfile = { workspace = true }
toml = { workspace = true }

[dev-dependencies]
async-trait = { workspace = true }
chrono = { workspace = true }
syn = { workspace = true }

[lints]
workspace = true
