[package]
name = "ryframe-generator"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
description.workspace = true

[dependencies]
ryframe-kernel = { path = "../ryframe-kernel" }
ryframe-tenant-db-migration = { path = "../ryframe-tenant-db-migration" }
sea-orm = { workspace = true }
serde = { workspace = true, features = ["derive"] }
tokio = { workspace = true, features = ["fs", "rt-multi-thread", "macros"] }

[[bin]]
name = "ryframe-gen"
path = "src/bin/gen.rs"

[lints]
workspace = true
