[package]
name = "ryframe-generator"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
description.workspace = true

[dependencies]
ryframe-kernel = { path = "../ryframe-kernel" }
ryframe-tenant-db = { path = "../ryframe-tenant-db" }
sea-orm = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
sha2 = { workspace = true }
hex = { workspace = true }
tempfile = { workspace = true }
toml = { workspace = true }

[dev-dependencies]
async-trait = { workspace = true }
chrono = { workspace = true }
syn = { workspace = true }

[lints]
workspace = true
