use sea_orm_migration::prelude::*;

/// 初始化所有业务表（对应 ryframe_config.sql）
pub struct Migration;

impl MigrationName for Migration {
    fn name(&self) -> &str {
        "m20260101_000001_init_tables"
    }
}

#[async_trait::async_trait]
impl MigrationTrait for Migration {
    async fn up(&self, manager: &SchemaManager) -> Result<(), DbErr> {
        // 1. 部门表
        manager
            .create_table(
                Table::create()
                    .table(SysDept::Table)
                    .if_not_exists()
                    .col(
                        ColumnDef::new(SysDept::Id)
                            .big_integer()
                            .not_null()
                            .primary_key(),
                    )
                    .col(ColumnDef::new(SysDept::Name).string_len(64).not_null())
                    .col(ColumnDef::new(SysDept::ParentId).big_integer())
                    .col(
                        ColumnDef::new(SysDept::Ancestors)
                            .string_len(512)
                            .not_null()
                            .default(""),
                    )
                    .col(
                        ColumnDef::new(SysDept::Sort)
                            .integer()
                            .not_null()
                            .default(0),
                    )
                    .col(
                        ColumnDef::new(SysDept::Status)
                            .char_len(1)
                            .not_null()
                            .default("1"),
                    )
                    .col(ColumnDef::new(SysDept::Remark).string_len(512))
                    .col(
                        ColumnDef::new(SysDept::DelFlag)
                            .char_len(1)
                            .not_null()
                            .default("0"),
                    )
                    .col(
                        ColumnDef::new(SysDept::CreatedAt)
                            .date_time()
                            .not_null()
                            .default(Expr::current_timestamp()),
                    )
                    .col(
                        ColumnDef::new(SysDept::UpdatedAt)
                            .date_time()
                            .not_null()
                            .default(Expr::current_timestamp()),
                    )
                    .to_owned(),
            )
            .await?;

        // 2. 用户表
        manager
            .create_table(
                Table::create()
                    .table(SysUser::Table)
                    .if_not_exists()
                    .col(
                        ColumnDef::new(SysUser::Id)
                            .big_integer()
                            .not_null()
                            .primary_key(),
                    )
                    .col(
                        ColumnDef::new(SysUser::Username)
                            .string_len(64)
                            .not_null()
                            .unique_key(),
                    )
                    .col(
                        ColumnDef::new(SysUser::PasswordHash)
                            .string_len(255)
                            .not_null(),
                    )
                    .col(ColumnDef::new(SysUser::Nickname).string_len(64).not_null())
                    .col(
                        ColumnDef::new(SysUser::Email)
                            .string_len(128)
                            .not_null()
                            .default(""),
                    )
                    .col(
                        ColumnDef::new(SysUser::Phone)
                            .string_len(32)
                            .not_null()
                            .default(""),
                    )
                    .col(ColumnDef::new(SysUser::Avatar).string_len(255))
                    .col(
                        ColumnDef::new(SysUser::Status)
                            .char_len(1)
                            .not_null()
                            .default("1"),
                    )
                    .col(ColumnDef::new(SysUser::DeptId).big_integer())
                    .col(ColumnDef::new(SysUser::Remark).string_len(512))
                    .col(ColumnDef::new(SysUser::LoginIp).string_len(128))
                    .col(ColumnDef::new(SysUser::LoginDate).date_time())
                    .col(
                        ColumnDef::new(SysUser::DelFlag)
                            .char_len(1)
                            .not_null()
                            .default("0"),
                    )
                    .col(
                        ColumnDef::new(SysUser::CreatedAt)
                            .date_time()
                            .not_null()
                            .default(Expr::current_timestamp()),
                    )
                    .col(
                        ColumnDef::new(SysUser::UpdatedAt)
                            .date_time()
                            .not_null()
                            .default(Expr::current_timestamp()),
                    )
                    .to_owned(),
            )
            .await?;

        // 3. 角色表
        manager
            .create_table(
                Table::create()
                    .table(SysRole::Table)
                    .if_not_exists()
                    .col(
                        ColumnDef::new(SysRole::Id)
                            .big_integer()
                            .not_null()
                            .primary_key(),
                    )
                    .col(ColumnDef::new(SysRole::Name).string_len(64).not_null())
                    .col(
                        ColumnDef::new(SysRole::Code)
                            .string_len(64)
                            .not_null()
                            .unique_key(),
                    )
                    .col(
                        ColumnDef::new(SysRole::DataScope)
                            .char_len(1)
                            .not_null()
                            .default("1"),
                    )
                    .col(
                        ColumnDef::new(SysRole::Status)
                            .char_len(1)
                            .not_null()
                            .default("1"),
                    )
                    .col(
                        ColumnDef::new(SysRole::Sort)
                            .integer()
                            .not_null()
                            .default(0),
                    )
                    .col(ColumnDef::new(SysRole::Remark).string_len(512))
                    .col(
                        ColumnDef::new(SysRole::DelFlag)
                            .char_len(1)
                            .not_null()
                            .default("0"),
                    )
                    .col(
                        ColumnDef::new(SysRole::CreatedAt)
                            .date_time()
                            .not_null()
                            .default(Expr::current_timestamp()),
                    )
                    .col(
                        ColumnDef::new(SysRole::UpdatedAt)
                            .date_time()
                            .not_null()
                            .default(Expr::current_timestamp()),
                    )
                    .to_owned(),
            )
            .await?;

        // 4. 权限表
        manager
            .create_table(
                Table::create()
                    .table(SysPermission::Table)
                    .if_not_exists()
                    .col(
                        ColumnDef::new(SysPermission::Id)
                            .big_integer()
                            .not_null()
                            .primary_key(),
                    )
                    .col(
                        ColumnDef::new(SysPermission::Name)
                            .string_len(64)
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(SysPermission::Code)
                            .string_len(128)
                            .not_null()
                            .unique_key(),
                    )
                    .col(ColumnDef::new(SysPermission::ParentId).big_integer())
                    .col(
                        ColumnDef::new(SysPermission::PermType)
                            .string_len(16)
                            .not_null(),
                    )
                    .col(ColumnDef::new(SysPermission::Path).string_len(255))
                    .col(ColumnDef::new(SysPermission::Icon).string_len(64))
                    .col(
                        ColumnDef::new(SysPermission::Sort)
                            .integer()
                            .not_null()
                            .default(0),
                    )
                    .col(
                        ColumnDef::new(SysPermission::Status)
                            .char_len(1)
                            .not_null()
                            .default("1"),
                    )
                    .col(
                        ColumnDef::new(SysPermission::CreatedAt)
                            .date_time()
                            .not_null()
                            .default(Expr::current_timestamp()),
                    )
                    .col(
                        ColumnDef::new(SysPermission::UpdatedAt)
                            .date_time()
                            .not_null()
                            .default(Expr::current_timestamp()),
                    )
                    .to_owned(),
            )
            .await?;

        // 5. 菜单表
        manager
            .create_table(
                Table::create()
                    .table(SysMenu::Table)
                    .if_not_exists()
                    .col(
                        ColumnDef::new(SysMenu::Id)
                            .big_integer()
                            .not_null()
                            .primary_key(),
                    )
                    .col(ColumnDef::new(SysMenu::Name).string_len(64).not_null())
                    .col(ColumnDef::new(SysMenu::ParentId).big_integer())
                    .col(ColumnDef::new(SysMenu::Path).string_len(255))
                    .col(ColumnDef::new(SysMenu::Component).string_len(255))
                    .col(ColumnDef::new(SysMenu::Icon).string_len(64))
                    .col(
                        ColumnDef::new(SysMenu::Sort)
                            .integer()
                            .not_null()
                            .default(0),
                    )
                    .col(
                        ColumnDef::new(SysMenu::Visible)
                            .boolean()
                            .not_null()
                            .default(true),
                    )
                    .col(
                        ColumnDef::new(SysMenu::Status)
                            .char_len(1)
                            .not_null()
                            .default("1"),
                    )
                    .col(
                        ColumnDef::new(SysMenu::DelFlag)
                            .char_len(1)
                            .not_null()
                            .default("0"),
                    )
                    .col(
                        ColumnDef::new(SysMenu::CreatedAt)
                            .date_time()
                            .not_null()
                            .default(Expr::current_timestamp()),
                    )
                    .col(
                        ColumnDef::new(SysMenu::UpdatedAt)
                            .date_time()
                            .not_null()
                            .default(Expr::current_timestamp()),
                    )
                    .to_owned(),
            )
            .await?;

        // 6. 岗位表
        manager
            .create_table(
                Table::create()
                    .table(SysPost::Table)
                    .if_not_exists()
                    .col(
                        ColumnDef::new(SysPost::Id)
                            .big_integer()
                            .not_null()
                            .primary_key(),
                    )
                    .col(ColumnDef::new(SysPost::Name).string_len(64).not_null())
                    .col(
                        ColumnDef::new(SysPost::Code)
                            .string_len(64)
                            .not_null()
                            .unique_key(),
                    )
                    .col(
                        ColumnDef::new(SysPost::Sort)
                            .integer()
                            .not_null()
                            .default(0),
                    )
                    .col(
                        ColumnDef::new(SysPost::Status)
                            .char_len(1)
                            .not_null()
                            .default("1"),
                    )
                    .col(ColumnDef::new(SysPost::Remark).string_len(512))
                    .col(
                        ColumnDef::new(SysPost::DelFlag)
                            .char_len(1)
                            .not_null()
                            .default("0"),
                    )
                    .col(
                        ColumnDef::new(SysPost::CreatedAt)
                            .date_time()
                            .not_null()
                            .default(Expr::current_timestamp()),
                    )
                    .col(
                        ColumnDef::new(SysPost::UpdatedAt)
                            .date_time()
                            .not_null()
                            .default(Expr::current_timestamp()),
                    )
                    .to_owned(),
            )
            .await?;

        // 7. 参数配置表
        manager
            .create_table(
                Table::create()
                    .table(SysConfig::Table)
                    .if_not_exists()
                    .col(
                        ColumnDef::new(SysConfig::Id)
                            .big_integer()
                            .not_null()
                            .primary_key(),
                    )
                    .col(ColumnDef::new(SysConfig::Name).string_len(128).not_null())
                    .col(
                        ColumnDef::new(SysConfig::Key)
                            .string_len(128)
                            .not_null()
                            .unique_key(),
                    )
                    .col(ColumnDef::new(SysConfig::Value).string_len(512).not_null())
                    .col(ColumnDef::new(SysConfig::Remark).string_len(512))
                    .col(
                        ColumnDef::new(SysConfig::DelFlag)
                            .char_len(1)
                            .not_null()
                            .default("0"),
                    )
                    .col(
                        ColumnDef::new(SysConfig::CreatedAt)
                            .date_time()
                            .not_null()
                            .default(Expr::current_timestamp()),
                    )
                    .col(
                        ColumnDef::new(SysConfig::UpdatedAt)
                            .date_time()
                            .not_null()
                            .default(Expr::current_timestamp()),
                    )
                    .to_owned(),
            )
            .await?;

        // 8. 字典类型表
        manager
            .create_table(
                Table::create()
                    .table(SysDictType::Table)
                    .if_not_exists()
                    .col(
                        ColumnDef::new(SysDictType::Id)
                            .big_integer()
                            .not_null()
                            .primary_key(),
                    )
                    .col(ColumnDef::new(SysDictType::Name).string_len(64).not_null())
                    .col(
                        ColumnDef::new(SysDictType::Code)
                            .string_len(64)
                            .not_null()
                            .unique_key(),
                    )
                    .col(
                        ColumnDef::new(SysDictType::Status)
                            .char_len(1)
                            .not_null()
                            .default("1"),
                    )
                    .col(ColumnDef::new(SysDictType::Remark).string_len(512))
                    .col(
                        ColumnDef::new(SysDictType::DelFlag)
                            .char_len(1)
                            .not_null()
                            .default("0"),
                    )
                    .col(
                        ColumnDef::new(SysDictType::CreatedAt)
                            .date_time()
                            .not_null()
                            .default(Expr::current_timestamp()),
                    )
                    .col(
                        ColumnDef::new(SysDictType::UpdatedAt)
                            .date_time()
                            .not_null()
                            .default(Expr::current_timestamp()),
                    )
                    .to_owned(),
            )
            .await?;

        // 9. 字典数据表
        manager
            .create_table(
                Table::create()
                    .table(SysDictData::Table)
                    .if_not_exists()
                    .col(
                        ColumnDef::new(SysDictData::Id)
                            .big_integer()
                            .not_null()
                            .primary_key(),
                    )
                    .col(
                        ColumnDef::new(SysDictData::TypeCode)
                            .string_len(64)
                            .not_null(),
                    )
                    .col(ColumnDef::new(SysDictData::Label).string_len(64).not_null())
                    .col(ColumnDef::new(SysDictData::Value).string_len(64).not_null())
                    .col(
                        ColumnDef::new(SysDictData::Sort)
                            .integer()
                            .not_null()
                            .default(0),
                    )
                    .col(
                        ColumnDef::new(SysDictData::Status)
                            .char_len(1)
                            .not_null()
                            .default("1"),
                    )
                    .col(ColumnDef::new(SysDictData::CssClass).string_len(64))
                    .col(ColumnDef::new(SysDictData::Remark).string_len(512))
                    .col(
                        ColumnDef::new(SysDictData::DelFlag)
                            .char_len(1)
                            .not_null()
                            .default("0"),
                    )
                    .col(
                        ColumnDef::new(SysDictData::CreatedAt)
                            .date_time()
                            .not_null()
                            .default(Expr::current_timestamp()),
                    )
                    .col(
                        ColumnDef::new(SysDictData::UpdatedAt)
                            .date_time()
                            .not_null()
                            .default(Expr::current_timestamp()),
                    )
                    .to_owned(),
            )
            .await?;

        // 10. 通知公告表
        manager
            .create_table(
                Table::create()
                    .table(SysNotice::Table)
                    .if_not_exists()
                    .col(
                        ColumnDef::new(SysNotice::Id)
                            .big_integer()
                            .not_null()
                            .primary_key(),
                    )
                    .col(ColumnDef::new(SysNotice::Title).string_len(128).not_null())
                    .col(ColumnDef::new(SysNotice::Content).text().not_null())
                    .col(ColumnDef::new(SysNotice::Type).string_len(16))
                    .col(
                        ColumnDef::new(SysNotice::Status)
                            .char_len(1)
                            .not_null()
                            .default("1"),
                    )
                    .col(ColumnDef::new(SysNotice::CreatedBy).big_integer())
                    .col(
                        ColumnDef::new(SysNotice::DelFlag)
                            .char_len(1)
                            .not_null()
                            .default("0"),
                    )
                    .col(
                        ColumnDef::new(SysNotice::CreatedAt)
                            .date_time()
                            .not_null()
                            .default(Expr::current_timestamp()),
                    )
                    .col(
                        ColumnDef::new(SysNotice::UpdatedAt)
                            .date_time()
                            .not_null()
                            .default(Expr::current_timestamp()),
                    )
                    .to_owned(),
            )
            .await?;

        // 11. 操作日志表
        manager
            .create_table(
                Table::create()
                    .table(SysOperLog::Table)
                    .if_not_exists()
                    .col(
                        ColumnDef::new(SysOperLog::Id)
                            .big_integer()
                            .not_null()
                            .primary_key(),
                    )
                    .col(ColumnDef::new(SysOperLog::Title).string_len(64).not_null())
                    .col(
                        ColumnDef::new(SysOperLog::BusinessType)
                            .string_len(32)
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(SysOperLog::Method)
                            .string_len(255)
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(SysOperLog::RequestMethod)
                            .string_len(16)
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(SysOperLog::OperName)
                            .string_len(64)
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(SysOperLog::OperUrl)
                            .string_len(255)
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(SysOperLog::OperIp)
                            .string_len(128)
                            .not_null(),
                    )
                    .col(ColumnDef::new(SysOperLog::OperLocation).string_len(128))
                    .col(ColumnDef::new(SysOperLog::OperParam).text())
                    .col(ColumnDef::new(SysOperLog::JsonResult).text())
                    .col(
                        ColumnDef::new(SysOperLog::Status)
                            .char_len(1)
                            .not_null()
                            .default("1"),
                    )
                    .col(ColumnDef::new(SysOperLog::ErrorMsg).text())
                    .col(ColumnDef::new(SysOperLog::OperTime).date_time().not_null())
                    .col(
                        ColumnDef::new(SysOperLog::CostTime)
                            .big_integer()
                            .not_null()
                            .default(0),
                    )
                    .to_owned(),
            )
            .await?;

        // 12. 登录信息表
        manager
            .create_table(
                Table::create()
                    .table(SysLoginInfo::Table)
                    .if_not_exists()
                    .col(
                        ColumnDef::new(SysLoginInfo::Id)
                            .big_integer()
                            .not_null()
                            .primary_key(),
                    )
                    .col(
                        ColumnDef::new(SysLoginInfo::UserName)
                            .string_len(64)
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(SysLoginInfo::Ipaddr)
                            .string_len(128)
                            .not_null(),
                    )
                    .col(ColumnDef::new(SysLoginInfo::LoginLocation).string_len(128))
                    .col(ColumnDef::new(SysLoginInfo::Browser).string_len(64))
                    .col(ColumnDef::new(SysLoginInfo::Os).string_len(64))
                    .col(
                        ColumnDef::new(SysLoginInfo::Status)
                            .char_len(1)
                            .not_null()
                            .default("1"),
                    )
                    .col(ColumnDef::new(SysLoginInfo::Msg).string_len(255))
                    .col(
                        ColumnDef::new(SysLoginInfo::LoginTime)
                            .date_time()
                            .not_null(),
                    )
                    .to_owned(),
            )
            .await?;

        // 13. 定时任务表
        manager
            .create_table(
                Table::create()
                    .table(SysJob::Table)
                    .if_not_exists()
                    .col(
                        ColumnDef::new(SysJob::Id)
                            .big_integer()
                            .not_null()
                            .primary_key(),
                    )
                    .col(
                        ColumnDef::new(SysJob::Name)
                            .string_len(64)
                            .not_null()
                            .unique_key(),
                    )
                    .col(
                        ColumnDef::new(SysJob::GroupName)
                            .string_len(64)
                            .not_null()
                            .default("system"),
                    )
                    .col(ColumnDef::new(SysJob::CronExpr).string_len(128).not_null())
                    .col(
                        ColumnDef::new(SysJob::MisfirePolicy)
                            .char_len(1)
                            .not_null()
                            .default("1"),
                    )
                    .col(
                        ColumnDef::new(SysJob::Concurrent)
                            .char_len(1)
                            .not_null()
                            .default("0"),
                    )
                    .col(
                        ColumnDef::new(SysJob::Status)
                            .char_len(1)
                            .not_null()
                            .default("1"),
                    )
                    .col(ColumnDef::new(SysJob::Remark).string_len(512))
                    .col(
                        ColumnDef::new(SysJob::CreateTime)
                            .date_time()
                            .not_null()
                            .default(Expr::current_timestamp()),
                    )
                    .col(
                        ColumnDef::new(SysJob::UpdateTime)
                            .date_time()
                            .not_null()
                            .default(Expr::current_timestamp()),
                    )
                    .to_owned(),
            )
            .await?;

        // 14. 定时任务日志表
        manager
            .create_table(
                Table::create()
                    .table(SysJobLog::Table)
                    .if_not_exists()
                    .col(
                        ColumnDef::new(SysJobLog::Id)
                            .big_integer()
                            .not_null()
                            .primary_key(),
                    )
                    .col(ColumnDef::new(SysJobLog::JobName).string_len(64).not_null())
                    .col(
                        ColumnDef::new(SysJobLog::JobGroup)
                            .string_len(64)
                            .not_null()
                            .default("system"),
                    )
                    .col(ColumnDef::new(SysJobLog::Message).text().not_null())
                    .col(
                        ColumnDef::new(SysJobLog::Status)
                            .char_len(1)
                            .not_null()
                            .default("0"),
                    )
                    .col(ColumnDef::new(SysJobLog::ErrorMsg).text())
                    .col(
                        ColumnDef::new(SysJobLog::CostMs)
                            .big_integer()
                            .not_null()
                            .default(0),
                    )
                    .col(ColumnDef::new(SysJobLog::StartTime).date_time().not_null())
                    .to_owned(),
            )
            .await?;

        // 15. 用户-角色关联表
        manager
            .create_table(
                Table::create()
                    .table(UserRole::Table)
                    .if_not_exists()
                    .col(ColumnDef::new(UserRole::UserId).big_integer().not_null())
                    .col(ColumnDef::new(UserRole::RoleId).big_integer().not_null())
                    .primary_key(Index::create().col(UserRole::UserId).col(UserRole::RoleId))
                    .to_owned(),
            )
            .await?;

        // 16. 角色-权限关联表
        manager
            .create_table(
                Table::create()
                    .table(RolePermission::Table)
                    .if_not_exists()
                    .col(
                        ColumnDef::new(RolePermission::RoleId)
                            .big_integer()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(RolePermission::PermId)
                            .big_integer()
                            .not_null(),
                    )
                    .primary_key(
                        Index::create()
                            .col(RolePermission::RoleId)
                            .col(RolePermission::PermId),
                    )
                    .to_owned(),
            )
            .await?;

        // 17. 角色-菜单关联表
        manager
            .create_table(
                Table::create()
                    .table(RoleMenu::Table)
                    .if_not_exists()
                    .col(ColumnDef::new(RoleMenu::RoleId).big_integer().not_null())
                    .col(ColumnDef::new(RoleMenu::MenuId).big_integer().not_null())
                    .primary_key(Index::create().col(RoleMenu::RoleId).col(RoleMenu::MenuId))
                    .to_owned(),
            )
            .await?;

        // 18. 角色-部门关联表（数据权限）
        manager
            .create_table(
                Table::create()
                    .table(SysRoleDept::Table)
                    .if_not_exists()
                    .col(ColumnDef::new(SysRoleDept::RoleId).big_integer().not_null())
                    .col(ColumnDef::new(SysRoleDept::DeptId).big_integer().not_null())
                    .primary_key(
                        Index::create()
                            .col(SysRoleDept::RoleId)
                            .col(SysRoleDept::DeptId),
                    )
                    .to_owned(),
            )
            .await?;

        Ok(())
    }

    async fn down(&self, manager: &SchemaManager) -> Result<(), DbErr> {
        // 按依赖关系反向删除
        let tables = [
            SysRoleDept::Table.into_table_ref(),
            RoleMenu::Table.into_table_ref(),
            RolePermission::Table.into_table_ref(),
            UserRole::Table.into_table_ref(),
            SysJobLog::Table.into_table_ref(),
            SysJob::Table.into_table_ref(),
            SysLoginInfo::Table.into_table_ref(),
            SysOperLog::Table.into_table_ref(),
            SysNotice::Table.into_table_ref(),
            SysDictData::Table.into_table_ref(),
            SysDictType::Table.into_table_ref(),
            SysConfig::Table.into_table_ref(),
            SysPost::Table.into_table_ref(),
            SysMenu::Table.into_table_ref(),
            SysPermission::Table.into_table_ref(),
            SysRole::Table.into_table_ref(),
            SysUser::Table.into_table_ref(),
            SysDept::Table.into_table_ref(),
        ];
        for table in tables {
            manager
                .drop_table(Table::drop().table(table).if_exists().to_owned())
                .await?;
        }
        Ok(())
    }
}

// ========== 表名枚举 ==========

#[derive(Iden)]
enum SysDept {
    Table,
    Id,
    Name,
    ParentId,
    Ancestors,
    Sort,
    Status,
    Remark,
    DelFlag,
    CreatedAt,
    UpdatedAt,
}

#[derive(Iden)]
enum SysUser {
    Table,
    Id,
    Username,
    PasswordHash,
    Nickname,
    Email,
    Phone,
    Avatar,
    Status,
    DeptId,
    Remark,
    LoginIp,
    LoginDate,
    DelFlag,
    CreatedAt,
    UpdatedAt,
}

#[derive(Iden)]
enum SysRole {
    Table,
    Id,
    Name,
    Code,
    DataScope,
    Status,
    Sort,
    Remark,
    DelFlag,
    CreatedAt,
    UpdatedAt,
}

#[derive(Iden)]
enum SysPermission {
    Table,
    Id,
    Name,
    Code,
    ParentId,
    PermType,
    Path,
    Icon,
    Sort,
    Status,
    CreatedAt,
    UpdatedAt,
}

#[derive(Iden)]
enum SysMenu {
    Table,
    Id,
    Name,
    ParentId,
    Path,
    Component,
    Icon,
    Sort,
    Visible,
    Status,
    DelFlag,
    CreatedAt,
    UpdatedAt,
}

#[derive(Iden)]
enum SysPost {
    Table,
    Id,
    Name,
    Code,
    Sort,
    Status,
    Remark,
    DelFlag,
    CreatedAt,
    UpdatedAt,
}

#[derive(Iden)]
#[iden = "sys_config"]
enum SysConfig {
    Table,
    Id,
    Name,
    #[iden = "key"]
    Key,
    Value,
    Remark,
    DelFlag,
    CreatedAt,
    UpdatedAt,
}

#[derive(Iden)]
enum SysDictType {
    Table,
    Id,
    Name,
    Code,
    Status,
    Remark,
    DelFlag,
    CreatedAt,
    UpdatedAt,
}

#[derive(Iden)]
enum SysDictData {
    Table,
    Id,
    TypeCode,
    Label,
    Value,
    Sort,
    Status,
    CssClass,
    Remark,
    DelFlag,
    CreatedAt,
    UpdatedAt,
}

#[derive(Iden)]
enum SysNotice {
    Table,
    Id,
    Title,
    Content,
    Type,
    Status,
    CreatedBy,
    DelFlag,
    CreatedAt,
    UpdatedAt,
}

#[derive(Iden)]
enum SysOperLog {
    Table,
    Id,
    Title,
    BusinessType,
    Method,
    RequestMethod,
    OperName,
    OperUrl,
    OperIp,
    OperLocation,
    OperParam,
    JsonResult,
    Status,
    ErrorMsg,
    OperTime,
    CostTime,
}

#[derive(Iden)]
enum SysLoginInfo {
    Table,
    Id,
    UserName,
    Ipaddr,
    LoginLocation,
    Browser,
    Os,
    Status,
    Msg,
    LoginTime,
}

#[derive(Iden)]
enum SysJob {
    Table,
    Id,
    Name,
    GroupName,
    CronExpr,
    MisfirePolicy,
    Concurrent,
    Status,
    Remark,
    CreateTime,
    UpdateTime,
}

#[derive(Iden)]
enum SysJobLog {
    Table,
    Id,
    JobName,
    JobGroup,
    Message,
    Status,
    ErrorMsg,
    CostMs,
    StartTime,
}

#[derive(Iden)]
enum UserRole {
    Table,
    UserId,
    RoleId,
}

#[derive(Iden)]
enum RolePermission {
    Table,
    RoleId,
    PermId,
}

#[derive(Iden)]
enum RoleMenu {
    Table,
    RoleId,
    MenuId,
}

#[derive(Iden)]
enum SysRoleDept {
    Table,
    RoleId,
    DeptId,
}
