pub mod background_job;
pub mod cache_namespace_version;
pub mod config;
pub mod dept;
pub mod dict_data;
pub mod dict_type;
pub mod export_job;
pub mod login_info;
pub mod menu;
pub mod message;
pub mod message_audience;
pub mod message_recipient;
pub mod notice;
pub mod oper_log;
pub mod outbox_event;
pub mod password_reset_request;
pub mod permission;
pub mod post;
pub mod role;
pub mod role_dept;
pub mod role_permission;
pub mod sys_file;
pub mod tenant;
pub mod user;
pub mod user_role;

pub use background_job::Entity as BackgroundJobEntity;
pub use cache_namespace_version::Entity as CacheNamespaceVersionEntity;
pub use config::Entity as ConfigEntity;
pub use dept::Entity as DeptEntity;
pub use export_job::Entity as ExportJobEntity;
pub use menu::Entity as MenuEntity;
pub use outbox_event::Entity as OutboxEventEntity;
pub use password_reset_request::Entity as PasswordResetRequestEntity;
pub use permission::Entity as PermissionEntity;
pub use post::Entity as PostEntity;
pub use role::Entity as RoleEntity;
pub use sys_file::Entity as SysFileEntity;
pub use tenant::Entity as TenantEntity;
pub use user::Entity as UserEntity;
