coverage:
  precision: 2
  round: down
  range: "65...90"
  status:
    project:
      default:
        target: 65%
        threshold: 1%
    patch:
      default:
        target: 80%
        threshold: 2%

comment:
  layout: "reach,diff,flags,files"
  require_changes: true

ignore:
  - "vendor/**"
  - "crates/ryframe-db-migration/**"
