[package]
name = "ryframe-monitor"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
description.workspace = true

[dependencies]
ryframe-http = { path = "../ryframe-http", features = ["openapi"] }
ryframe-kernel = { path = "../ryframe-kernel" }
ryframe-core = { path = "../ryframe-core" }
ryframe-middleware = { path = "../ryframe-middleware" }
# 由 ryframe-macro 生成的 `#[perm]` 路由展开所需。
ryframe-auth = { path = "../ryframe-auth" }
ryframe-macro = { path = "../ryframe-macro" }
serde = { workspace = true, features = ["derive"] }
sysinfo = { workspace = true }
axum = { workspace = true }
serde_json = { workspace = true }
chrono = { workspace = true }
redis = { workspace = true }
tracing = { workspace = true }
utoipa = { workspace = true }
tokio = { workspace = true, features = ["rt"] }

[dev-dependencies]
tokio = { workspace = true, features = ["macros", "rt"] }

[lints]
workspace = true
