[package]
name = "ryframe-excel"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
description = "RyFrame Excel 导入导出组件"

[dependencies]
ryframe-kernel = { path = "../ryframe-kernel" }
calamine = { workspace = true }
rust_xlsxwriter = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }

[lints]
workspace = true
