[package]
name = "ryframe-db"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
description.workspace = true

[features]
default = []
telemetry = ["dep:opentelemetry", "dep:opentelemetry-semantic-conventions"]

[dependencies]
ryframe-kernel = { path = "../ryframe-kernel" }
ryframe-application = { path = "../ryframe-application", default-features = false }
ryframe-config = { path = "../ryframe-config" }
ryframe-macro = { path = "../ryframe-macro" }
sea-orm = { workspace = true }
sea-orm-migration = { workspace = true }
async-trait = { workspace = true }
futures-util = { workspace = true }
log = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true, features = ["registry", "std", "fmt"] }
opentelemetry = { workspace = true, optional = true }
opentelemetry-semantic-conventions = { workspace = true, optional = true }
serde = { workspace = true ,features = ["derive"]}
serde_json = { workspace = true }
toml = { workspace = true }
chrono = {workspace = true,features = ["serde"]}
tokio = { workspace = true, features = ["time"] }

[dev-dependencies]
tokio = { workspace = true, features = ["macros", "rt-multi-thread", "sync", "time"] }

[[bin]]
name = "export_mysql_snapshot"
path = "src/bin/export_mysql_snapshot.rs"
test = false

[lints]
workspace = true
