[package]
name = "ryframe-common"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
description.workspace = true

[dependencies]
serde = { workspace = true, features = ["derive"] }
ryframe-kernel = { path = "../ryframe-kernel" }
ryframe-http = { path = "../ryframe-http" }
ryframe-utils = { path = "../ryframe-utils" }
ryframe-captcha = { path = "../ryframe-captcha" }
ryframe-excel = { path = "../ryframe-excel" }
ryframe-mail = { path = "../ryframe-mail" }
ryframe-i18n = { path = "../ryframe-i18n" }
dashmap = {workspace = true}
tracing = {workspace = true}
toml = {workspace = true}

[dev-dependencies]
axum = { workspace = true }
serde_json = { workspace = true }
tempfile = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt"] }
