[package]
name = "order-business"
version = "0.1.0"
edition = "2024"

[package.metadata.ryframe]
kind = "business"
module = "order"

[features]
default = ["api", "migration"]
catalog = []
persistence = ["ryframe-sdk/persistence", "dep:sea-orm"]
api = ["persistence", "ryframe-sdk/api", "dep:serde", "dep:utoipa", "dep:validator"]
migration = ["persistence", "ryframe-sdk/migration"]

[dependencies]
ryframe-sdk = { path = "../ryframe-sdk", default-features = false }
sea-orm = { workspace = true, optional = true }
serde = { workspace = true, optional = true }
utoipa = { workspace = true, optional = true }
validator = { workspace = true, optional = true }

[lints]
workspace = true
