[package]
name = "ryframe-auth"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
description.workspace = true

[dependencies]
ryframe-kernel = { path = "../ryframe-kernel" }
jsonwebtoken = { workspace = true, features = ["aws_lc_rs"] }
argon2 = { workspace = true }
rand = { workspace = true }
serde = { workspace = true, features = ["derive"] }
chrono = { workspace = true, features = ["serde"] }
uuid = { workspace = true, features = ["v4"] }
lazy_static = { workspace = true }

[lints]
workspace = true
