[package]
name = "ryframe-application"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
description.workspace = true

[dependencies]
ryframe-kernel = { path = "../ryframe-kernel" }
ryframe-db = { path = "../ryframe-db" }
ryframe-auth = { path = "../ryframe-auth" }
async-trait = { workspace = true }
futures-util = { workspace = true }
base64 = { workspace = true }
hmac = { workspace = true }
rand = { workspace = true }
zip = { workspace = true }
chrono = { workspace = true, features = ["serde"] }
chrono-tz = { workspace = true }
cron = { workspace = true }
sea-orm = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
tokio = { workspace = true, features = ["fs", "io-util", "macros", "rt", "sync", "time"] }
tracing = { workspace = true }
sha2 = { workspace = true }
hex = { workspace = true }
uuid = { workspace = true, features = ["v4", "v7"] }
validator = { workspace = true, features = ["derive"] }
opentelemetry = { workspace = true }
tracing-opentelemetry = { workspace = true }

[lints]
workspace = true
