use super::super::ResourceIr;
use super::{GeneratedAsset, slice};
use crate::AssetRoot;

/// 沿用 `example` 的职责划分，并统一收进 `src/generated`，保护手写目录。
pub(crate) fn render_business_resource(resource: &ResourceIr) -> Vec<GeneratedAsset> {
    let name = &resource.name;
    let header = format!(
        "// @generated by RyFrame {}\n// resource: {name}\n// source: Rust ResourceModel\n// 请勿手工修改；修改 resources/ 后重新生成。\n\n",
        crate::GENERATOR_VERSION,
    );
    let model_path = format!("crate::generated::models::{name}");
    let model = format!(
        "{header}pub mod model {{\n{}\n}}\n\npub mod port {{\n{}\n}}\n\npub use model::*;\npub use port::*;\n",
        application_content(slice::application_model(resource, "")),
        application_content(slice::application_port(resource, "")),
    );
    let mut assets = vec![
        asset(resource, format!("src/generated/models/{name}.rs"), model),
        asset(
            resource,
            format!("src/generated/services/{name}.rs"),
            service_content(slice::application_service(resource, &header), name),
        ),
        asset(
            resource,
            format!("src/generated/entities/{name}.rs"),
            shared_content(slice::database_entity(resource, &header)),
        ),
        asset(
            resource,
            format!("src/generated/repositories/{name}.rs"),
            persistence_content(
                slice::database_repository(resource, &[resource], &header),
                &model_path,
                name,
            ),
        ),
        asset(
            resource,
            format!("src/generated/dto/{name}.rs"),
            api_content(slice::api_dto(resource, &header), &model_path, name),
        ),
        asset(
            resource,
            format!("src/generated/handlers/{name}.rs"),
            handler_content(resource, &header, &model_path),
        ),
        asset(
            resource,
            format!("src/generated/openapi/{name}.rs"),
            api_content(slice::api_openapi(resource, &header), &model_path, name),
        ),
    ];
    if resource.bootstrap_migration {
        assets.push(asset(
            resource,
            format!("migrations/{}.rs", slice::migration_name(resource)),
            migration_content(slice::migration(resource, &header)),
        ));
    }
    assets
}

fn asset(resource: &ResourceIr, path: String, content: String) -> GeneratedAsset {
    GeneratedAsset {
        resource: resource.name.clone(),
        root: AssetRoot::Backend,
        path,
        content,
    }
}

fn application_content(content: String) -> String {
    shared_content(content)
        .replace(
            "crate::validated_tenant_id",
            "ryframe_sdk::validated_tenant_id",
        )
        .replace("crate::next_id", "ryframe_sdk::next_id")
        .replace(
            "crate::{TransactionAuditMode, complete_transaction}",
            "ryframe_sdk::{TransactionAuditMode, complete_transaction}",
        )
        .replace(
            "use crate::PersistenceTransaction;",
            "use ryframe_sdk::PersistenceTransaction;",
        )
}

fn service_content(content: String, name: &str) -> String {
    application_content(content)
        .replace(
            "use super::model::",
            &format!("use crate::generated::models::{name}::"),
        )
        .replace(
            "use super::port::",
            &format!("use crate::generated::models::{name}::"),
        )
}

fn persistence_content(content: String, model_path: &str, name: &str) -> String {
    shared_content(content)
        .replace(
            &format!("ryframe_application::generated::{name}"),
            model_path,
        )
        .replace(&format!("ryframe_sdk::generated::{name}"), model_path)
        .replace(
            "use super::entity;",
            &format!("use crate::generated::entities::{name} as entity;"),
        )
        .replace(
            "use crate::DbResultExt;",
            "use ryframe_sdk::persistence::DbResultExt;",
        )
        .replace(
            "crate::ControlDatabaseCluster",
            "ryframe_sdk::persistence::ControlDatabaseCluster",
        )
        .replace(
            "crate::TenantDatabaseRouter",
            "ryframe_sdk::persistence::TenantDatabaseRouter",
        )
        .replace(
            "crate::TenantDataError",
            "ryframe_sdk::persistence::TenantDataError",
        )
        .replace(
            "ryframe_db::ReadConsistency",
            "ryframe_sdk::persistence::ReadConsistency",
        )
        .replace(
            "ryframe_db::pagination",
            "ryframe_sdk::persistence::pagination",
        )
}

fn api_content(content: String, model_path: &str, name: &str) -> String {
    shared_content(content)
        .replace(
            &format!("ryframe_application::generated::{name}"),
            model_path,
        )
        .replace(&format!("ryframe_sdk::generated::{name}"), model_path)
        .replace(
            &format!(
                "{model_path}::{}Service",
                crate::naming::to_pascal_case(name)
            ),
            &format!(
                "crate::generated::services::{name}::{}Service",
                crate::naming::to_pascal_case(name)
            ),
        )
        .replace(
            "use super::dto::",
            &format!("use crate::generated::dto::{name}::"),
        )
        .replace(
            "use crate::RequestPrincipal;",
            "use ryframe_sdk::api::RequestPrincipal;",
        )
        .replace(
            "use crate::handler_utils::parse_id;",
            "use ryframe_sdk::api::parse_id;",
        )
        .replace("use crate::http::", "use ryframe_sdk::api::http::")
        .replace("crate::http::", "ryframe_sdk::api::http::")
        .replace("use ryframe_macro::{", "use ryframe_sdk::{")
        .replace(
            "super::handler::",
            &format!("crate::generated::handlers::{name}::"),
        )
        .replace("super::dto::", &format!("crate::generated::dto::{name}::"))
        .replace("serde_json::", "ryframe_sdk::serde_json::")
}

fn handler_content(resource: &ResourceIr, header: &str, model_path: &str) -> String {
    let content = api_content(
        slice::api_handler(resource, header),
        model_path,
        &resource.name,
    );
    let content = content
        .lines()
        .filter(|line| {
            let trimmed = line.trim_start();
            ![
                "#[get(",
                "#[post(",
                "#[put(",
                "#[patch(",
                "#[delete(",
                "#[perm(",
            ]
            .iter()
            .any(|prefix| trimmed.starts_with(prefix))
                && !trimmed.starts_with("use ryframe_sdk::{delete,")
        })
        .collect::<Vec<_>>()
        .join("\n");
    let permissions = &resource.access.permissions;
    format!(
        "use ryframe_sdk::api::perm_route;\nuse ryframe_sdk::axum::routing::{{delete, get, post, put}};\n{content}\n"
    )
    .replace(
        ".merge(route!(list))",
        &format!(
            ".route(\"/\", perm_route(get(list), {:?}))",
            permissions.list
        ),
    )
    .replace(
        ".merge(route!(detail))",
        &format!(
            ".route(\"/{{id}}\", perm_route(get(detail), {:?}))",
            permissions.read
        ),
    )
    .replace(
        ".merge(route!(create))",
        &format!(
            ".route(\"/\", perm_route(post(create), {:?}))",
            permissions.create
        ),
    )
    .replace(
        ".merge(route!(update))",
        &format!(
            ".route(\"/{{id}}\", perm_route(put(update), {:?}))",
            permissions.update
        ),
    )
    .replace(
        ".merge(route!(remove))",
        &format!(
            ".route(\"/{{id}}\", perm_route(delete(remove), {:?}))",
            permissions.delete
        ),
    )
}

fn migration_content(content: String) -> String {
    shared_content(content)
        .replace("use sea_orm::", "use ryframe_sdk::persistence::sea_orm::")
        .replace(
            "use sea_orm_migration::",
            "use ryframe_sdk::persistence::sea_orm_migration::",
        )
        .replace("#[async_trait::async_trait]", "#[ryframe_sdk::async_trait]")
}

fn shared_content(content: String) -> String {
    content
        .replace("ryframe_kernel::", "ryframe_sdk::")
        .replace("ryframe_application::", "ryframe_sdk::")
        .replace(
            "use async_trait::async_trait;",
            "use ryframe_sdk::async_trait;",
        )
        .replace("use sea_orm::", "use ryframe_sdk::persistence::sea_orm::")
        .replace("use serde::", "use ryframe_sdk::serde::")
        .replace("use utoipa::", "use ryframe_sdk::utoipa::")
        .replace("use axum::", "use ryframe_sdk::axum::")
        .replace("#[utoipa::", "#[ryframe_sdk::utoipa::")
        .replace("validator::", "ryframe_sdk::validator::")
        .replace("chrono::", "ryframe_sdk::chrono::")
}
