use super::ResourceIr;

pub(super) fn crud_resource_metadata(resource: &ResourceIr) -> serde_json::Value {
    let fields = resource
        .fields
        .iter()
        .filter(|field| {
            field.usage.create
                || field.usage.update
                || field.usage.read
                || field.usage.list
                || field.usage.filter
                || field.usage.sort
        })
        .map(|field| {
            let mut validation = serde_json::json!({
                "required": field.validation.required,
                "min_length": field.validation.min_length,
                "max_length": field.validation.max_length,
                "minimum": field.validation.minimum,
                "maximum": field.validation.maximum,
            });
            if let Some(minimum) = field.validation.min_utf8_bytes {
                validation
                    .as_object_mut()
                    .expect("校验元数据必须是对象")
                    .insert("min_utf8_bytes".into(), minimum.into());
            }
            if let Some(maximum) = field.validation.max_utf8_bytes {
                validation
                    .as_object_mut()
                    .expect("校验元数据必须是对象")
                    .insert("max_utf8_bytes".into(), maximum.into());
            }
            serde_json::json!({
                "name": field.name,
                "value_type": field.value_type,
                "wire_type": field.wire_type,
                "nullable": field.nullable,
                "order": field.order,
                "usage": &field.usage,
                "validation": validation,
                "labels": &field.labels,
                "widget": field.widget,
                "enum_values": &field.enum_values,
            })
        })
        .collect::<Vec<_>>();
    let mut metadata = serde_json::json!({
        "name": resource.name,
        "module": resource.module,
        "profile": resource.profile,
        "storage": resource.storage,
        "api": &resource.api,
        "access": &resource.access,
        "extension_permissions": &resource.extension_permissions,
        "menu": &resource.menu,
        "route": &resource.route,
        "labels": &resource.labels,
        "fields": fields,
    });
    if !resource.relations.is_empty() {
        metadata
            .as_object_mut()
            .expect("资源元数据必须是对象")
            .insert("relations".into(), serde_json::json!(resource.relations));
    }
    metadata
}

pub(super) fn access_catalog(resources: &[&ResourceIr], source: &str) -> String {
    let sources = if source.is_empty() {
        "# sources:".to_owned()
    } else {
        format!("# sources: {source}")
    };
    let mut output = format!(
        "# @generated by RyFrame {}\n{}\n# 请勿手工修改；修改 catalog/resources/*.toml 后重新生成。\n\nversion = 1\n",
        crate::GENERATOR_VERSION,
        sources,
    );
    for (index, resource) in resources.iter().enumerate() {
        if index > 0 {
            output.push('\n');
        }
        output.push_str("[[resources]]\n");
        output.push_str(&format!("name = {:?}\n", resource.name));
        output.push_str(&format!("module = {:?}\n", resource.module));
        if let Some(capability) = &resource.access.capability {
            output.push_str(&format!("capability = {capability:?}\n"));
        }
        output.push_str("[resources.labels]\n");
        output.push_str(&format!("zh_cn = {:?}\n", resource.labels.zh_cn));
        output.push_str(&format!("en = {:?}\n", resource.labels.en));
        output.push_str("[resources.menu]\n");
        output.push_str(&format!("key = {:?}\n", resource.menu.key));
        output.push_str(&format!("parent = {:?}\n", resource.menu.parent));
        output.push_str(&format!("order = {}\n", resource.menu.order));
        if let Some(icon) = &resource.menu.icon {
            output.push_str(&format!("icon = {icon:?}\n"));
        }
        output.push_str("[resources.menu.labels]\n");
        output.push_str(&format!("zh_cn = {:?}\n", resource.menu.labels.zh_cn));
        output.push_str(&format!("en = {:?}\n", resource.menu.labels.en));
        output.push_str("[resources.route]\n");
        output.push_str(&format!("key = {:?}\n", resource.route.key));
        output.push_str(&format!("path = {:?}\n", resource.route.path));
        output.push_str("[resources.permissions]\n");
        output.push_str(&format!(
            "create = {:?}\nread = {:?}\nlist = {:?}\nupdate = {:?}\ndelete = {:?}\n",
            resource.access.permissions.create,
            resource.access.permissions.read,
            resource.access.permissions.list,
            resource.access.permissions.update,
            resource.access.permissions.delete,
        ));
        output.push_str("[resources.extension_permissions]\n");
        for (name, permission) in &resource.extension_permissions {
            output.push_str(&format!("{name} = {permission:?}\n"));
        }
    }
    output
}
