use crate::{naming, schema::TableInfo, template};

pub fn render_dto(table: &TableInfo, base_name: &str) -> String {
    let struct_name = naming::to_pascal_case(base_name);
    let command_columns = template::command_columns(table).collect::<Vec<_>>();
    let request_fields = command_columns
        .iter()
        .map(|column| {
            format!(
                "    pub {}: {},",
                naming::safe_field_name(&column.name),
                column.rust_type
            )
        })
        .collect::<Vec<_>>()
        .join("\n");
    let chrono_import = template::chrono_import(command_columns.into_iter());

    format!(
        r#"// @generated by ryframe-generator v{generator_version}
{chrono_import}use serde::Deserialize;
use utoipa::ToSchema;

#[derive(Debug, Deserialize, validator::Validate, ToSchema)]
#[serde(deny_unknown_fields)]
pub struct Create{struct_name}Dto {{
{request_fields}
}}

#[derive(Debug, Deserialize, validator::Validate, ToSchema)]
#[serde(deny_unknown_fields)]
pub struct Update{struct_name}Dto {{
{request_fields}
}}
"#,
        generator_version = crate::GENERATOR_VERSION,
    )
}
