use crate::{naming, schema::TableInfo, template};

pub fn render_entity(table: &TableInfo, _base_name: &str, generate_comments: bool) -> String {
    let fields = table
        .columns
        .iter()
        .map(|column| {
            let field_name = naming::safe_field_name(&column.name);
            let mut attributes = Vec::new();
            if column.is_primary_key {
                attributes.push(format!(
                    "    #[sea_orm(primary_key, auto_increment = {})]",
                    column.is_auto_increment
                ));
                if !column.is_auto_increment && column.rust_type == "i64" {
                    attributes.push("    #[auto_fill(snowflake)]".into());
                }
            }
            if column.is_unique {
                attributes.push("    #[sea_orm(unique)]".into());
            }
            if generate_comments
                && let Some(comment) = column.comment.as_deref().filter(|value| !value.is_empty())
            {
                attributes.push(format!("    /// {}", one_line(comment)));
            }
            attributes.push(format!("    pub {}: {},", field_name, column.rust_type));
            attributes.join("\n")
        })
        .collect::<Vec<_>>()
        .join("\n");

    let table_doc = if generate_comments {
        table
            .comment
            .as_deref()
            .filter(|value| !value.is_empty())
            .map(|comment| format!("/// {}\n", one_line(comment)))
            .unwrap_or_default()
    } else {
        String::new()
    };
    let chrono_import = template::chrono_import(table.columns.iter());

    format!(
        r#"// @generated by ryframe-generator v{generator_version}
{chrono_import}use ryframe_macro::AutoFill;
use sea_orm::entity::prelude::*;
use serde::{{Deserialize, Serialize}};

{table_doc}#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize, AutoFill)]
#[sea_orm(table_name = "{table_name}")]
pub struct Model {{
{fields}
}}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {{}}

impl ActiveModelBehavior for ActiveModel {{}}
"#,
        generator_version = crate::GENERATOR_VERSION,
        table_name = table.table_name,
    )
}

fn one_line(value: &str) -> String {
    value.split_whitespace().collect::<Vec<_>>().join(" ")
}
