use crate::{naming, schema::TableInfo};

pub fn render_entity(table: &TableInfo, base_name: &str, generate_comments: bool) -> String {
    let _struct_name = naming::to_pascal_case(base_name);
    let fields: String = table
        .columns
        .iter()
        .map(|c| {
            let field_name = naming::safe_field_name(&c.name);
            let mut attrs = Vec::new();
            if c.is_primary_key {
                attrs.push("#[sea_orm(primary_key, auto_increment = false)]".to_string());
                attrs.push("#[auto_fill(snowflake)]".to_string());
            }
            if c.is_unique {
                attrs.push("#[sea_orm(unique)]".to_string());
            }
            // 宏缩进处理：每个属性前加 4 空格
            let attr_str = if attrs.is_empty() {
                String::new()
            } else {
                attrs
                    .iter()
                    .map(|a| format!("    {}\n", a))
                    .collect::<String>()
            };
            // 注释在宏下方
            let field_doc = if generate_comments {
                match &c.comment {
                    Some(comment) if !comment.is_empty() => format!("    /// {}\n", comment),
                    _ => "    /// \n".to_string(),
                }
            } else {
                String::new()
            };
            format!(
                "{}{}    pub {}: {},",
                attr_str, field_doc, field_name, c.rust_type
            )
        })
        .collect::<Vec<_>>()
        .join("\n");

    let table_doc = if generate_comments {
        match &table.comment {
            Some(comment) if !comment.is_empty() => format!("/// {}\n", comment),
            _ => "/// \n".to_string(),
        }
    } else {
        String::new()
    };

    format!(
        r#"// Generated by ryframe-generator v{} — depends on: ryframe-macro::AutoFill
use chrono::{{DateTime, Utc}};
use ryframe_macro::AutoFill;
use sea_orm::entity::prelude::*;
use serde::{{Deserialize, Serialize}};

{table_doc}#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize, AutoFill)]
#[sea_orm(table_name = "{table_name}")]
pub struct Model {{
{fields}
}}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {{}}

impl ActiveModelBehavior for ActiveModel {{}}
"#,
        crate::GENERATOR_VERSION,
        table_name = table.table_name,
        fields = fields
    )
}
