use crate::{naming, schema::TableInfo, template};

pub fn render_repository(table: &TableInfo, base_name: &str) -> String {
    let struct_name = naming::to_pascal_case(base_name);
    let snake = naming::to_snake_case(base_name);
    let primary_key = template::primary_key(table);
    let primary_key_type = primary_key.rust_type.as_str();
    let primary_key_field = naming::safe_field_name(&primary_key.name);
    let tenant_column = table
        .columns
        .iter()
        .find(|column| column.name == "tenant_id");
    let delete_column = table
        .columns
        .iter()
        .find(|column| column.name == "del_flag");
    let updated_at_column = table
        .columns
        .iter()
        .find(|column| column.name == "updated_at");
    let tenant_parameter = if tenant_column.is_some() {
        "tenant_id"
    } else {
        "_tenant_id"
    };

    let mut scope_filters = Vec::new();
    if tenant_column.is_some() {
        scope_filters.push(format!(".filter({snake}::Column::TenantId.eq(tenant_id))"));
    }
    if let Some(column) = delete_column {
        scope_filters.push(format!(
            ".filter({snake}::Column::DelFlag.eq({}))",
            template::normal_value(column)
        ));
    }
    let find_filters = scope_filters
        .iter()
        .map(|filter| format!("\n            {filter}"))
        .collect::<String>();

    let tenant_guard = tenant_column
        .map(|_| {
            r#"        if entity.tenant_id != tenant_id {
            return Err(AppError::Authorization(
                "不能修改其他租户的数据".into(),
            ));
        }
"#
        })
        .unwrap_or_default();
    let tenant_delete_filter = tenant_column
        .map(|_| format!("\n            .filter({snake}::Column::TenantId.eq(tenant_id))"))
        .unwrap_or_default();

    let delete_body = if let Some(column) = delete_column {
        let updated_at_expr = updated_at_column
            .filter(|column| column.rust_type.contains("DateTime<Utc>"))
            .map(|_| {
                format!(
                    "\n            .col_expr(\n                {snake}::Column::UpdatedAt,\n                sea_orm::sea_query::Expr::value(chrono::Utc::now()),\n            )"
                )
            })
            .unwrap_or_default();
        format!(
            r#"        let result = {snake}::Entity::update_many()
            .col_expr(
                {snake}::Column::DelFlag,
                sea_orm::sea_query::Expr::value({deleted_value}),
            ){updated_at_expr}
            .filter({snake}::Column::{primary_key_column}.eq(id))
            .filter({snake}::Column::DelFlag.eq({normal_value})){tenant_delete_filter}
            .exec(db)
            .await
            .map_err(|error| AppError::Database(error.to_string()))?;
        if result.rows_affected == 0 {{
            return Err(AppError::NotFound("记录不存在".into()));
        }}
        Ok(())"#,
            deleted_value = template::deleted_value(column),
            normal_value = template::normal_value(column),
            primary_key_column = naming::to_pascal_case(&primary_key.name),
        )
    } else {
        format!(
            r#"        let result = {snake}::Entity::delete_many()
            .filter({snake}::Column::{primary_key_column}.eq(id)){tenant_delete_filter}
            .exec(db)
            .await
            .map_err(|error| AppError::Database(error.to_string()))?;
        if result.rows_affected == 0 {{
            return Err(AppError::NotFound("记录不存在".into()));
        }}
        Ok(())"#,
            primary_key_column = naming::to_pascal_case(&primary_key.name),
        )
    };

    format!(
        r#"// @generated by ryframe-generator v{generator_version}
use async_trait::async_trait;
use ryframe_common::{{AppError, AppResult}};
use ryframe_core::repository::{{PageQuery, PageResult, Repository}};
use sea_orm::{{ActiveModelTrait, ColumnTrait, DatabaseConnection, EntityTrait, QueryFilter}};

use crate::entities::{snake};

pub struct {struct_name}Repository;

#[async_trait]
impl Repository<{snake}::Model, {primary_key_type}> for {struct_name}Repository {{
    async fn find_by_id(
        &self,
        db: &DatabaseConnection,
        {tenant_parameter}: &str,
        id: {primary_key_type},
    ) -> AppResult<Option<{snake}::Model>> {{
        {snake}::Entity::find_by_id(id){find_filters}
            .one(db)
            .await
            .map_err(|error| AppError::Database(error.to_string()))
    }}

    async fn find_by_page(
        &self,
        db: &DatabaseConnection,
        {tenant_parameter}: &str,
        query: PageQuery,
    ) -> AppResult<PageResult<{snake}::Model>> {{
        let select = {snake}::Entity::find(){find_filters};
        crate::pagination::paginate(db, select, &query).await
    }}

    async fn insert(
        &self,
        db: &DatabaseConnection,
        {tenant_parameter}: &str,
        entity: {snake}::Model,
    ) -> AppResult<{snake}::Model> {{
{tenant_guard}        let active: {snake}::ActiveModel = entity.into();
        active
            .insert(db)
            .await
            .map_err(|error| AppError::Database(error.to_string()))
    }}

    async fn update(
        &self,
        db: &DatabaseConnection,
        {tenant_parameter}: &str,
        entity: {snake}::Model,
    ) -> AppResult<{snake}::Model> {{
{tenant_guard}        let id = entity.{primary_key_field}.clone();
        if self.find_by_id(db, {tenant_parameter}, id).await?.is_none() {{
            return Err(AppError::NotFound("记录不存在".into()));
        }}
        let active: {snake}::ActiveModel = entity.into();
        active
            .update(db)
            .await
            .map_err(|error| AppError::Database(error.to_string()))
    }}

    async fn delete(
        &self,
        db: &DatabaseConnection,
        {tenant_parameter}: &str,
        id: {primary_key_type},
    ) -> AppResult<()> {{
{delete_body}
    }}
}}
"#,
        generator_version = crate::GENERATOR_VERSION,
    )
}
