[package]
name = "ryframe-business-db"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
ryframe-business-application = { path = "../ryframe-business-application" }
ryframe-application = { path = "../../ryframe-application", default-features = false }
ryframe-db = { path = "../../ryframe-db", default-features = false, features = ["repositories"] }
ryframe-tenant-db = { path = "../../ryframe-tenant-db", default-features = false, features = ["repositories"] }
ryframe-kernel = { path = "../../ryframe-kernel" }
sea-orm.workspace = true
async-trait.workspace = true
chrono.workspace = true
sea-orm-migration = { workspace = true, optional = true }

[features]
default = ["repositories"]
repositories = []
migration = ["dep:sea-orm-migration"]

[lints]
workspace = true
