# 开发环境配置
# 仅覆盖与默认值不同的项

[app]
name = "ryframe"
version = "0.1.0"
host = "0.0.0.0"
port = 8081

[database]
# 开发环境输出 SQL 摘要日志
# off = 关闭 | summary = SQL+耗时+行数 | full = 含完整SQL
sql_log_level = "full"

# 开发环境数据库连接
# 第一个为主数据库，后续为额外数据源
[[database.connections]]
driver = "mysql"
host = "localhost"
port = 3306
database = "ryframe_config"
username = "root"
password = "123456"
max_connections = 10
min_connections = 1

# 额外数据库
[[database.connections]]
driver = "mysql"
host = "localhost"
port = 3306
database = "ryframe_device"
username = "root"
password = "123456"
max_connections = 5
min_connections = 1

[redis]
host = "127.0.0.1"
port = 6379
password = "yecy"
database = 0

[cors]
allow_origins = ["http://localhost:5173", "http://localhost:3000"]

[logger]
level = "debug"