[package]
name = "ryframe-macro"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
description = "ryframe 属性宏（AutoFill derive 等）"

[lib]
proc-macro = true

[dependencies]
ryframe-core = { path = "../ryframe-core" }
syn = { workspace = true }
quote = { workspace = true }
proc-macro2 = { workspace = true }

[dev-dependencies]
ryframe-utils = { path = "../ryframe-utils" }
axum.workspace = true
chrono.workspace = true

[lints]
workspace = true
