use std::path::Path;

use sha2::{Digest, Sha256};

use super::catalog::load_descriptors;
use super::model::{descriptor_to_ir, selected_names};
use super::writer::{BusinessAsset, install_assets};
use super::{
    BusinessPackage, OwnedResourceDescriptor, locate_business_package,
};
use crate::{ResourceError, ResourceIr, StorageKind};

#[derive(Clone, Debug)]
pub struct BusinessGenerateOptions<'a> {
    pub current_dir: &'a Path,
    pub package: &'a str,
    pub model: Option<&'a str>,
    pub write: bool,
}

#[derive(Clone, Debug, Default)]
pub struct BusinessGenerateReport {
    pub created: Vec<String>,
    pub updated: Vec<String>,
    pub removed: Vec<String>,
    pub unchanged: Vec<String>,
}

pub fn generate_business_package(
    options: BusinessGenerateOptions<'_>,
) -> Result<BusinessGenerateReport, ResourceError> {
    let package = locate_business_package(options.current_dir, options.package)?;
    let descriptors = load_descriptors(&package)?;
    if descriptors.is_empty() {
        return Err(error("业务 crate 没有声明任何 ResourceModel"));
    }
    let selected = selected_names(&descriptors, options.model)?;
    let resources = descriptors
        .iter()
        .map(|descriptor| descriptor_to_ir(&package, descriptor))
        .collect::<Result<Vec<_>, _>>()?;
    let mut assets = Vec::new();
    for resource in &resources {
        if selected.contains(&resource.name) {
            assets.extend(
                crate::resource::render_business_resource(resource)
                    .into_iter()
                    .map(|asset| BusinessAsset::new(asset.resource, asset.path, asset.content)),
            );
        }
    }
    let aggregate = aggregate_assets(&package, &resources, &descriptors, &assets)?;
    assets.extend(aggregate);
    install_assets(&package, &selected, assets, options.write)
}

fn aggregate_assets(
    package: &BusinessPackage,
    resources: &[ResourceIr],
    descriptors: &[OwnedResourceDescriptor],
    resource_assets: &[BusinessAsset],
) -> Result<Vec<BusinessAsset>, ResourceError> {
    let resource_modules = resources
        .iter()
        .map(|resource| format!("pub mod {};", resource.name))
        .collect::<Vec<_>>()
        .join("\n");
    let descriptor_values = resources
        .iter()
        .zip(descriptors)
        .map(|(resource, descriptor)| format!("    {},", descriptor_literal(resource, descriptor)))
        .collect::<Vec<_>>()
        .join("\n");
    let routes = resources
        .iter()
        .map(|resource| {
            let database = match resource.storage {
                StorageKind::ControlRow => "context.control_database.clone()",
                StorageKind::TenantData => "context.tenant_database.clone()",
            };
            format!(
                "    let service = std::sync::Arc::new(services::{name}::{pascal}Service::new(repositories::{name}::port({database})));\n    router = router.nest(\"/{module}/{name}\", handlers::{name}::router(service, context.state.settings.pagination));",
                name = resource.name,
                pascal = resource.pascal_name,
                module = package.module,
            )
        })
        .collect::<Vec<_>>()
        .join("\n");
    let openapi = resources
        .iter()
        .map(|resource| {
            format!(
                "    document.merge(<openapi::{name}::{pascal}OpenApi as ryframe_sdk::utoipa::OpenApi>::openapi());",
                name = resource.name,
                pascal = resource.pascal_name,
            )
        })
        .collect::<Vec<_>>()
        .join("\n");
    let openapi_resources = resources
        .iter()
        .map(|resource| {
            format!(
                "        openapi::{name}::crud_resource_metadata(),",
                name = resource.name,
            )
        })
        .collect::<Vec<_>>()
        .join("\n");
    let count = resources.len();
    let generated = format!(
        "// @generated by RyFrame {}\n// 请勿手工修改。\n\n#[cfg(feature = \"api\")]\npub mod dto;\n#[cfg(feature = \"persistence\")]\npub mod entities;\n#[cfg(feature = \"api\")]\npub mod handlers;\n#[cfg(feature = \"persistence\")]\npub mod models;\n#[cfg(feature = \"api\")]\npub mod openapi;\n#[cfg(feature = \"persistence\")]\npub mod repositories;\n#[cfg(feature = \"persistence\")]\npub mod services;\n#[cfg(feature = \"migration\")]\npub mod migrations;\n\npub static RESOURCES: [ryframe_sdk::ResourceDescriptor; {count}] = [\n{descriptor_values}\n];\n\n#[cfg(feature = \"api\")]\npub fn routes(context: ryframe_sdk::BusinessRuntimeContext) -> ryframe_sdk::AppResult<ryframe_sdk::axum::Router> {{\n    let mut router = ryframe_sdk::axum::Router::new();\n{routes}\n    Ok(router)\n}}\n\n#[cfg(feature = \"api\")]\npub fn openapi() -> ryframe_sdk::OpenApiDocument {{\n    let mut document = ryframe_sdk::OpenApiDocument::default();\n{openapi}\n    document.extensions.get_or_insert_default().insert(\n        \"x-ryframe-crud-resources\".into(),\n        ryframe_sdk::serde_json::json!({{\n            \"version\": 1,\n            \"resources\": [\n{openapi_resources}\n            ]\n        }}),\n    );\n    document\n}}\n",
        crate::GENERATOR_VERSION,
    );
    let descriptor_json = serde_json::to_string_pretty(&serde_json::json!({
        "format_version": 1,
        "module": package.module,
        "resources": descriptors,
    }))
    .map_err(|serialize| error(format!("前端资源描述序列化失败：{serialize}")))?
        + "\n";
    let mut assets = vec![
        BusinessAsset::new("__catalog__", "src/generated/mod.rs", generated),
        BusinessAsset::new(
            "__catalog__",
            "src/generated/resources.json",
            descriptor_json,
        ),
    ];
    for directory in [
        "dto",
        "entities",
        "handlers",
        "models",
        "openapi",
        "repositories",
        "services",
    ] {
        assets.push(BusinessAsset::new(
            "__catalog__",
            format!("src/generated/{directory}/mod.rs"),
            format!(
                "// @generated by RyFrame {}\n// 请勿手工修改。\n\n{resource_modules}\n",
                crate::GENERATOR_VERSION,
            ),
        ));
    }
    assets.push(BusinessAsset::new(
        "__catalog__",
        "src/generated/migrations/mod.rs",
        migration_registry(package, resources, resource_assets)?,
    ));
    Ok(assets)
}

fn migration_registry(
    package: &BusinessPackage,
    resources: &[ResourceIr],
    assets: &[BusinessAsset],
) -> Result<String, ResourceError> {
    let mut modules = Vec::new();
    let mut entries = Vec::new();
    for resource in resources.iter().filter(|resource| resource.bootstrap_migration) {
        let migration = format!("m_resource_initial_{}", resource.name);
        let path = format!("migrations/{migration}.rs");
        let content = assets
            .iter()
            .find(|asset| asset.path == path)
            .ok_or_else(|| error(format!("缺少业务迁移资产 {path}")))?;
        let checksum = hex::encode(Sha256::digest(content.content.as_bytes()));
        let scope = match resource.storage {
            StorageKind::ControlRow => "Control",
            StorageKind::TenantData => "Tenant",
        };
        modules.push(format!(
            "#[path = \"../../../migrations/{migration}.rs\"]\nmod {migration};\nconst _: bool = {migration}::INITIAL_RESOURCE_MIGRATION;"
        ));
        entries.push(format!(
            "        std::sync::Arc::new(ryframe_sdk::SeaOrmBusinessMigration::new({:?}, {:?}, {:?}, None, {:?}, ryframe_sdk::BusinessMigrationScope::{scope}, {migration}::Migration)),",
            package.module, migration, checksum, resource.schema_hash,
        ));
    }
    Ok(format!(
        "// @generated by RyFrame {}\n// 请勿手工修改。\n\n{}\n\npub fn migrations() -> Vec<std::sync::Arc<dyn ryframe_sdk::BusinessMigration>> {{\n    vec![\n{}\n    ]\n}}\n",
        crate::GENERATOR_VERSION,
        modules.join("\n"),
        entries.join("\n"),
    ))
}

fn descriptor_literal(resource: &ResourceIr, descriptor: &OwnedResourceDescriptor) -> String {
    let database = match resource.storage {
        StorageKind::ControlRow => "ryframe_sdk::ResourceDatabase::Control",
        StorageKind::TenantData => "ryframe_sdk::ResourceDatabase::Tenant",
    };
    let fields = descriptor
        .fields
        .iter()
        .map(|field| {
            format!(
                "ryframe_sdk::ResourceFieldDescriptor {{ name: {:?}, column: {:?}, rust_type: {:?}, rename_from: {}, default: {}, primary_key: {}, generated: {}, read_only: {}, filter: {}, sort: {}, unique: {} }}",
                field.name,
                field.column,
                field.rust_type,
                option_literal(field.rename_from.as_deref()),
                option_literal(field.default.as_deref()),
                field.primary_key,
                field.generated,
                field.read_only,
                field.filter,
                field.sort,
                field.unique,
            )
        })
        .collect::<Vec<_>>()
        .join(", ");
    format!(
        "ryframe_sdk::ResourceDescriptor {{ name: {:?}, title: {:?}, table: {:?}, database: {database}, model_module: {:?}, model_type: {:?}, route: {}, menu_parent: {}, menu_order: {}, fields: &[{fields}] }}",
        descriptor.name,
        descriptor.title,
        descriptor.table,
        descriptor.model_module,
        descriptor.model_type,
        option_literal(descriptor.route.as_deref()),
        option_literal(descriptor.menu_parent.as_deref()),
        descriptor.menu_order,
    )
}

fn option_literal(value: Option<&str>) -> String {
    value.map_or_else(|| "None".into(), |value| format!("Some({value:?})"))
}

fn error(message: impl Into<String>) -> ResourceError {
    ResourceError::new(message, "修正业务 ResourceModel 后重新运行 cargo generate")
}
