apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ryframe.fullname" . }}-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ryframe.labels" . | nindent 4 }}
type: Opaque
stringData:
  jwt-secret: {{ .Values.auth.jwtSecret | quote }}
  db-password: {{ .Values.mysql.external.password | quote }}
  redis-password: {{ .Values.redis.external.password | quote }}
  {{- with .Values.otel }}
  {{- if .enabled }}
  otel-endpoint: {{ .endpoint | quote }}
  {{- end }}
  {{- end }}
