use super::{TaskDefinition, TaskExecutor, TaskRepository, TaskStage, TaskWorkingDirectory};

pub(super) const TASKS: [TaskDefinition; 19] = [
    task_definition!(
        CiFrontendSource,
        "ci.frontend-source",
        "select_frontend_source",
        "从已校验的 CI 事件选择配套前端引用",
        CrossRepository,
        Prerequisite,
        Backend,
        None,
        &[],
        &["GitHub job output"],
        &[]
    ),
    task_definition!(
        CiFrontendCandidateSource,
        "ci.frontend-source-candidate",
        "select_frontend_source_with_candidate",
        "生成候选 OpenAPI 并选择精确配套前端引用",
        CrossRepository,
        Contract,
        Backend,
        None,
        &["ryframe export_openapi（与 API 共用业务模块注册表）"],
        &[
            "Cargo target/ci/backend",
            "候选 OpenAPI",
            "GitHub job output"
        ],
        &[]
    ),
    task_definition!(
        CiFrontendCheckout,
        "ci.frontend-checkout",
        "verify_frontend_checkout",
        "核对 CI 选择的精确前端提交",
        Frontend,
        Prerequisite,
        Frontend,
        None,
        &[],
        &[],
        &[]
    ),
    task_definition!(
        CiContractSource,
        "ci.contract-source",
        "verify_formal_contract_source",
        "核对正式消费者契约来源",
        CrossRepository,
        Contract,
        Frontend,
        None,
        &[],
        &[],
        &[]
    ),
    task_definition!(
        CiWindowsSmoke,
        "ci.windows-smoke",
        "run_windows_smoke",
        "执行 Windows Rust 和进程生命周期 smoke",
        CrossRepository,
        Test,
        Backend,
        None,
        &["Windows API、xtask 与资源 Workspace"],
        &["Cargo target"],
        &[]
    ),
    task_definition!(
        CiResourceGate,
        "ci.resource-gate",
        "run_resource_gate",
        "执行资源影响闭包与对应门禁",
        CrossRepository,
        Test,
        Backend,
        None,
        &["资源反向依赖闭包"],
        &["Cargo target", "资源门禁报告"],
        &[]
    ),
    task_definition!(
        CiIntegration,
        "ci.integration",
        "run_integration",
        "执行真实协议集成门禁",
        Backend,
        Test,
        Backend,
        None,
        &["MySQL、Redis 与 TLS 真实协议目标"],
        &["Cargo target", "隔离测试资源"],
        &["已登记的 MySQL、Redis 与 TLS 测试资源"]
    ),
    task_definition!(
        CiRequiredJobs,
        "ci.required-jobs",
        "verify_required_jobs",
        "核对 Required 汇总与动态 CI 计划一致",
        Backend,
        Static,
        Backend,
        None,
        &[],
        &[],
        &[]
    ),
    task_definition!(
        CiSupplyChainSource,
        "ci.security.supply-chain",
        "verify_supply_chain_source",
        "核对供应链策略和条件依赖例外",
        Backend,
        Static,
        Backend,
        Some(&["tools/python/check_supply_chain.py", "--verify-cargo-graph"]),
        &["Cargo feature graph"],
        &["Cargo registry cache"],
        &["Cargo registry"]
    ),
    task_definition!(
        CiCargoAudit,
        "ci.security.audit",
        "run_cargo_audit",
        "核对 RustSec 安全公告",
        Backend,
        Static,
        Backend,
        Some(&["audit", "--deny", "warnings"]),
        &[],
        &["RustSec advisory cache"],
        &["RustSec advisory database"]
    ),
    task_definition!(
        CiCargoDeny,
        "ci.security.deny",
        "run_cargo_deny",
        "核对依赖许可证、禁用项和来源",
        Backend,
        Static,
        Backend,
        Some(&["deny", "check", "licenses", "bans", "sources"]),
        &[],
        &["Cargo registry cache"],
        &["Cargo registry"]
    ),
    task_definition!(
        CiCycloneDxReport,
        "ci.security.report.cyclonedx",
        "verify_cyclonedx_report",
        "核对单个 CycloneDX 报告",
        Backend,
        Static,
        Backend,
        None,
        &[],
        &[],
        &[]
    ),
    task_definition!(
        CiTrivyReport,
        "ci.security.report.trivy",
        "verify_trivy_report",
        "核对单个 Trivy 漏洞报告",
        Backend,
        Static,
        Backend,
        None,
        &[],
        &[],
        &[]
    ),
    task_definition!(
        CiDeploymentChanges,
        "ci.security.deployment.changes",
        "detect_deployment_changes",
        "按精确 base/head 保守判定部署资产变化",
        Backend,
        Static,
        Backend,
        None,
        &[],
        &["GitHub job output"],
        &[]
    ),
    task_definition!(
        CiDeploymentStatic,
        "ci.security.deployment.static",
        "verify_deployment_source",
        "核对部署资产静态边界",
        Backend,
        Static,
        Backend,
        Some(&["tools/python/check_deployment_assets.py"]),
        &[],
        &[],
        &[]
    ),
    task_definition!(
        CiDeploymentCompose,
        "ci.security.deployment.compose",
        "verify_deployment_compose",
        "核对生产 Compose 展开结果",
        Backend,
        Static,
        Backend,
        None,
        &[],
        &["Docker state"],
        &["Docker daemon"]
    ),
    task_definition!(
        CiDeploymentNginx,
        "ci.security.deployment.nginx",
        "verify_deployment_nginx",
        "核对生产 Nginx 配置",
        Backend,
        Static,
        Backend,
        None,
        &[],
        &["Runner temporary certificate", "Docker state"],
        &["Docker daemon"]
    ),
    task_definition!(
        CiDeploymentPrometheus,
        "ci.security.deployment.prometheus",
        "verify_deployment_prometheus",
        "核对 Prometheus 规则和测试",
        Backend,
        Static,
        Backend,
        None,
        &[],
        &["Docker state"],
        &["Docker daemon"]
    ),
    task_definition!(
        CiDeploymentImage,
        "ci.security.deployment.image",
        "verify_deployment_image",
        "核对生产镜像内容与提交身份",
        Backend,
        Build,
        Backend,
        None,
        &[],
        &["target/image-inspection", "Docker state"],
        &["Docker daemon"]
    ),
];
