mod authorization_diagnostic;
mod captcha;
mod config;
mod data_retention;
mod dept;
mod dict;
mod export;
mod file;
mod log_time_range;
mod login_info;
mod menu;
mod message;
mod online_user;
mod oper_log;
mod option;
mod overview;
mod permission;
mod post_export;
mod product;
mod product_capability_catalog;
mod profile;
mod role;
mod service_account;
mod tenant;
mod user;
mod user_import;
mod websocket_ticket;

pub mod content;
pub mod identity;
pub mod operations;
pub mod platform;
