[package]
name = "ryframe-http"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
description = "RyFrame HTTP 边界适配与统一响应"

[features]
default = []
openapi = ["dep:utoipa"]

[dependencies]
ryframe-kernel = { path = "../ryframe-kernel" }
axum = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
http = { workspace = true }
tracing = { workspace = true }
utoipa = { workspace = true, optional = true }
validator = { workspace = true }
