use utoipa::OpenApi;

#[derive(OpenApi)]
#[openapi(
    paths(
        crate::handlers::service_account_handler::list_accounts,
        crate::handlers::service_account_handler::create_account,
        crate::handlers::service_account_handler::account_detail,
        crate::handlers::service_account_handler::update_account,
        crate::handlers::service_account_handler::update_account_status,
        crate::handlers::service_account_handler::remove_account,
        crate::handlers::service_account_handler::account_roles,
        crate::handlers::service_account_handler::replace_account_roles,
        crate::handlers::service_account_handler::list_credentials,
        crate::handlers::service_account_handler::create_credential,
        crate::handlers::service_account_handler::revoke_credential,
        crate::handlers::service_account_handler::list_delegations,
        crate::handlers::service_account_handler::revoke_delegation,
        crate::handlers::service_account_handler::list_access_audits,
        crate::handlers::service_delegation_profile_handler::list_my_delegations,
        crate::handlers::service_delegation_profile_handler::delegation_capabilities,
        crate::handlers::service_delegation_profile_handler::create_my_delegation,
        crate::handlers::service_delegation_profile_handler::revoke_my_delegation,
        crate::handlers::agent_handler::capabilities,
        crate::handlers::agent_handler::users,
        crate::handlers::agent_handler::departments,
        crate::handlers::agent_handler::posts,
        crate::handlers::agent_handler::dictionary
    ),
    components(schemas(
        crate::dto::service_account_dto::ServiceResourcePageQuery,
        crate::dto::service_account_dto::CreateServiceAccountDto,
        crate::dto::service_account_dto::UpdateServiceAccountDto,
        crate::dto::service_account_dto::ServiceAccountStatusDto,
        crate::dto::service_account_dto::UpdateServiceAccountStatusDto,
        crate::dto::service_account_dto::ReplaceServiceAccountRolesDto,
        crate::dto::service_account_dto::CreateServiceCredentialDto,
        crate::dto::service_account_dto::CreateServiceDelegationDto,
        crate::dto::public_dto::ServiceCapabilityVo,
        crate::dto::public_dto::ServiceAccountVo,
        crate::dto::public_dto::ServiceAccountDetailVo,
        crate::dto::public_dto::ServiceCredentialVo,
        crate::dto::public_dto::CreatedServiceCredentialVo,
        crate::dto::public_dto::ServiceDelegationVo,
        crate::dto::public_dto::CreatedServiceDelegationVo,
        crate::dto::public_dto::ServiceAccessAuditVo,
        crate::handlers::service_delegation_profile_handler::ServiceDelegationTargetResponse,
        crate::dto::agent_dto::AgentPageQuery,
        crate::dto::agent_dto::AgentCapabilityResponse,
        crate::dto::agent_dto::AgentUserResponse,
        crate::dto::agent_dto::AgentDepartmentResponse,
        crate::dto::agent_dto::AgentPostResponse,
        crate::dto::agent_dto::AgentDictionaryResponse,
        crate::dto::agent_dto::AgentDictionaryItemResponse
    ))
)]
struct ServiceDoc;

pub(super) fn document() -> utoipa::openapi::OpenApi {
    ServiceDoc::openapi()
}
