[package]
name = "ryframe-business-api"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
ryframe-business-application = { path = "../ryframe-business-application" }
ryframe-api = { path = "../../ryframe-api", default-features = false }
ryframe-kernel = { path = "../../ryframe-kernel" }
ryframe-macro = { path = "../../ryframe-macro" }
axum = { workspace = true, features = ["json"] }
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
utoipa.workspace = true
validator.workspace = true
chrono.workspace = true

[[bin]]
name = "export_business_openapi"
path = "src/bin/export_business_openapi.rs"
test = false

[lints]
workspace = true
