[package]
name = "ryframe-mail"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
description = "RyFrame SMTP 邮件组件"

[dependencies]
lettre = { workspace = true }
tracing = { workspace = true }

[lints]
workspace = true
